---
- name: Configuration management
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Install Tree
      yum:
        name: Tree
        state: present
    - name: HTTPD
      yum:
        name: HTTPD
        state: present
    - name: Start Apache HTTP Server service
      systemd:
        name: httpd
        enabled: yes
        state: started
