---
- name: Configuration management
  hosts: jenkins
  become: yes
  gather_facts: yes
  tasks:
    - name: GIT Install
      yum:
        name: git
        state: present
    - name: Clone Git Repo
      shell: git clone https://github.com/NirmalKumaran-2106/StartUp-Commands
    - name: Folder Access
      shell: cd /home/ec2-user/StartUp-Commands
    - name: Authorize
      shell: sudo chmod 777 jenkins_master.sh
    - name: Remove Files
      shell: sudo rm -rf ansible_master.sh terraform_slave.sh
    - name: Execute Initial Configuration
      shell: ./jenkins_master.sh