---
- name: Configuration management
  hosts: slave
  become: yes
  gather_facts: yes
  tasks:
    - name: GIT Install
      yum:
        name: git
        state: present
    - name: Clone Git Repo
      git:
        repo: https://github.com/NirmalKumaran-2106/StartUp-Commands.git
        dest: /home/ec2-user/
        force: yes
    - name: Authorize
      shell: sudo chmod 777 /home/ec2-user/StartUp-Commands/terraform_slave.sh
    - name: Remove Files
      shell: |
        sudo rm -rf /home/ec2-user/StartUp-Commands/ansible_master.sh
        sudo rm -rf /home/ec2-user/StartUp-Commands/terraform_slave.sh
        sudo rm -rf /home/ec2-user/StartUp-Commands/README.md
        sudo rm -rf /home/ec2-user/StartUp-Commands/Jenkinsfile
    - name: Execute Initial Configuration
      shell: /home/ec2-user/StartUp-Commands/./terraform_slave.sh