---
- name: Configuration management
  hosts: ansible
  become: yes
  gather_facts: yes
  tasks:
    - name: GIT Install
      yum:
        name: git
        state: present
    - name: Clone Git Repo
      shell: git clone https://github.com/NirmalKumaran-2106/StartUp-Commands
    - name: Authorize
      shell: sudo chmod 777 /home/ec2-user/StartUp-Commands/ansible_master.sh
    - name: Remove Files
      shell: 
        sudo rm -rf /home/ec2-user/StartUp-Commands/terraform_slave.sh
        sudo rm -rf /home/ec2-user/StartUp-Commands/terraform_slave.sh
        sudo rm -rf /home/ec2-user/StartUp-Commands/README.md
        sudo rm -rf /home/ec2-user/StartUp-Commands/Jenkinsfile
    - name: Execute Initial Configuration
      shell: /home/ec2-user/StartUp-Commands/./ansible_master.sh